export const MEAL_HISTORY = {
  TITLE: 'Meal analyses',
  SUBTITLE: 'Pending meals stay here after you snap a plate. Upgrade, then tap Analyze to finish.',
  EMPTY_TITLE: 'No saved meals yet',
  EMPTY_BODY: 'Snap a plate while signed in and your photo will appear here until analysis is complete.',
  EMPTY_CTA: 'Snap a plate',
  EMPTY_CTA_HREF: '/snap',
  STATUS_PENDING: 'Pending',
  STATUS_DONE: 'Done',
  STATUS_FAILED: 'Failed',
  ANALYZE_PENDING: 'Analyze meal',
  VIEW_RESULTS: 'View results',
  RETRY: 'Try again',
  SAVED_AT: 'Saved',
  MEAL_PREVIEW_ALT: 'Saved meal photo',
  LOAD_ERROR: 'Could not load meal history.',
  REMOVE_PENDING_ARIA: 'Remove pending meal',
  REMOVE_ERROR: 'Could not remove that meal.',
  PENDING_COUNT_LABEL: 'pending',
} as const;
